from backgammon_config import *

MENU_BORDER_THICKNESS = 0.02
MENU_BG_START_COLOR = (0.6, 0.5, 0.3, 1)
MENU_BG_END_COLOR = (0.5, 0.4, 0.2, 1)
MENU_BORDER_COLOR = (0.7, 0.6, 0.4, 1)


TITLE_TOP_SPACER = 0.15
TITLE_PROPORTION = 0.1
TITLE_TEXT = 'Backgammon'
TITLE_FONT = 'Helvetica'
TITLE_COLOR = (220, 220, 220, 255)

SUBTITLE_OFFSET = 0.2
SUBTITLE_TOP_SPACER = 0.03
SUBTITLE_PROPORTION = 0.03
SUBTITLE_TEXT = '...the awesome edition!'
SUBTITLE_FONT = 'Helvetica'
SUBTITLE_COLOR = (230, 230, 230, 255)

BUTTON_MAIN_WIDTH = 0.35
BUTTON_MAIN_HEIGHT = 0.06
BUTTON_MAIN_CORNER_RADIUS = 0.2
BUTTON_MAIN_TOP_SPACER = 0.50
BUTTON_MAIN_LEFT_SPACER = 0.13
BUTTON_MAIN_HORIZONTAL_SPACER = 0.04
BUTTON_MAIN_VERTICAL_SPACER = 0.03

BUTTON_MAIN_TEXT_NEW = 'New Game'
BUTTON_MAIN_TEXT_RESET = 'Reset Statistic'
BUTTON_MAIN_TEXT_ABOUT = 'About'
BUTTON_MAIN_TEXT_EXIT = 'Quit Game'

BUTTON_TEXT_PROPORTION = 0.4
BUTTON_TEXT_FONT = 'Helvetica'
BUTTON_BG_COLOR = (0.5, 0.3, 0.1, 1)
BUTTON_FG_COLOR = (230, 230, 230, 255)
BUTTON_BG_HOVER_COLOR = (0.55, 0.35, 0.15, 1)
BUTTON_FG_HOVER_COLOR = (240, 240, 240, 255)
BUTTON_BG_PRESS_COLOR = (0.48, 0.28, 0.08, 1)
BUTTON_FG_PRESS_COLOR = (220, 220, 220, 255)


STATISTIC_LEFT_SPACER = 0
STATISTIC_TOP_SPACER = 0.72
STATISTIC_WIDTH_PERCENTAGE = 1
STATISTIC_HEIGHT_PERCENTAGE = 0.28
STATISTIC_TEXT_PERCENTAGE = 0.25
STATISTIC_FG_COLOR = (220, 220, 220, 255)

STATISTIC_TITLE_TEXT = 'Game Statistic'
STATISTIC_TITLE_FONT = 'Arial'
STATISTIC_TITLE_COLOR = (100, 60, 20, 255)

STATISTIC_CONTAINER_COLOR = (0.65, 0.55, 0.35, 1)
STATISTIC_TABLE_FONT = 'Arial'
STATISTIC_TABLE_BORDER = 2
STATISTIC_HEADER_WIDTH_PERCENTAGE = 0.3
STATISTIC_HEADER_HEIGHT_PERCENTAGE = 0.3
STATISTIC_HEADER_BG_COLOR = (1, 1, 1, 0.04)
STATISTIC_HEADER_FG_COLOR = (255, 255, 255, 255)

STATISTIC_PROPERTY_GAMES_NR = 'Games Played'
STATISTIC_PROPERTY_WINS = 'Wins'
STATISTIC_PROPERTY_LOSSES = 'Losses'
STATISTIC_LEVEL1 = 'Easy'
STATISTIC_LEVEL2 = 'Normal'
STATISTIC_LEVEL3 = 'Hard'


DIALOG_WIDTH_PERCENTAGE = 0.7
DIALOG_HEIGHT_PERCENTAGE = 0.6
DIALOG_BORDER_THICKNESS = 5

DIALOG_BORDER_COLOR = (1, 1, 1, 0.3)
DIALOG_BG_COLOR = (0.8, 0.8, 0.8, 1)

DIALOG_TITLE_TOP_SPACER = 0.08
DIALOG_TITLE_PERCENTAGE = 0.05
DIALOG_TITLE_FONT = 'Helvetica'
DIALOG_TITLE_COLOR = (50, 50, 50, 255)

DIALOG_TITLE_NEW_GAME = 'Choose the game difficulty'
DIALOG_TITLE_ABOUT = 'About us'

DIALOG_BUTTON_WIDTH_PERCENTAGE = 0.5
DIALOG_BUTTON_HEIGHT_PERCENTAGE = 0.1
DIALOG_CLOSE_BUTTON_SPACER = 0.08

DIALOG_CLOSE_BUTTON_TEXT = 'Close this dialog'

if __name__=="__main__":
    print "This is a configuration class, do not run it directly."
